name: backend

on:
  push:
    branches:
      - main
  schedule:
    # 日本時間で毎晩21時
    - cron: '0 12 * * *'

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm ci
      - run: npm run test -- --coverage
      - run: npm run build

      # buildしたファイルに移動
      - run: node dist/index.js &
      # & はnode dist/index.jsをバックグラウンドで起動して、その実行中に別のコマンドを起動できるようにする

      - run: npx wait-on -t 10000 http://localhost:8080/api/health
      - run: npm run test:api

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: backend/coverage/**
          retention-days: 5
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: backend/dist/index.js
          retention-days: 5